server.port=${SERVER_PORT}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB}

app.session.ttl=${APP_USER_SESSION_TTL}
