server.port=${SERVER_PORT}

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DB}

spring.data.mongodb.host=${MONGODB_HOST}
spring.data.mongodb.port=${MONGODB_PORT}
spring.data.mongodb.database=${MONGODB_DATABASE}
spring.data.mongodb.username=${MONGODB_USER}
spring.data.mongodb.password=${MONGODB_PASSWORD}
spring.data.mongodb.authentication-database=${MONGODB_AUTH_DATABASE}

app.session.ttl=${APP_USER_SESSION_TTL}
app.like.ttl=${APP_LIKE_TTL}
app.event.categories=${APP_EVENT_CATEGORIES:meetup,concert,exhibition,party,other}

spring.data.mongodb.auto-index-creation=true

spring.cassandra.contact-points=${CASSANDRA_HOSTS}
spring.cassandra.port=${CASSANDRA_PORT}
spring.cassandra.local-datacenter=${CASSANDRA_LOCAL_DATACENTER}
spring.cassandra.keyspace-name=${CASSANDRA_KEYSPACE}
spring.cassandra.schema-action=none
